- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.surisetty.online
  tasks:
  - name: Install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable mysql server
    ansible.builtin.dnf:
     name: mysqld
     state: latest
     enabled: yes

# check password already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_connect_check

  - name: print output
    ansible.builtin.debug:
      msg: "output>>>>>> {{mysql_connect_check}}"