- name: install and run nginx
  hosts: localhost
  connection: local
  become: no
  tasks:
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
